In [2]:
import pandas as pd
district1 = pd.read_csv("SWVF_1_22.txt")
district2 = pd.read_csv("SWVF_23_44.txt")
district3 = pd.read_csv("SWVF_45_66.txt")
district4 = pd.read_csv("SWVF_67_88.txt")

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (20,25,26,58,64,74,78,82,87,93) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (20,25,26,58,64,73,74,75,78,82,87,93,96,97,100) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (20,25,26,60,73,75,78,97) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (20,25,26,58,64,74,75,78,82,87,93,97) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
sample1 = district1.sample(frac=1)
sample2 = district2.sample(frac=1)
sample3 = district3.sample(frac=1)
sample4 = district4.sample(frac=1)

In [4]:
sample1 = sample1.head(500)
sample1

,SOS_VOTERID,COUNTY_NUMBER,COUNTY_ID,LAST_NAME,FIRST_NAME,MIDDLE_NAME,SUFFIX,DATE_OF_BIRTH,REGISTRATION_DATE,VOTER_STATUS,...,GENERAL-11/03/2015,PRIMARY-03/15/2016,GENERAL-06/07/2016,PRIMARY-09/13/2016,GENERAL-11/08/2016,PRIMARY-05/02/2017,PRIMARY-09/12/2017,GENERAL-11/07/2017,PRIMARY-05/08/2018,GENERAL-08/07/2018
1589051,OH0016465400,21,98871,BROWN,HELEN,V,NaN,1930-07-31,2000-07-31,ACTIVE,...,X,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
148478,OH0023001783,6,51247,SNEARY,JEFFERY,S,NaN,1965-06-01,2014-11-07,ACTIVE,...,NaN,R,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
2017695,OH0016361359,2,28178,MUSSER,WARREN,C,NaN,1935-05-12,1969-11-01,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,X,R,NaN
1128282,OH0021885757,18,2541383,PINCKNEY,BRITANY,NaN,NaN,1992-09-20,2012-08-16,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1952509,OH0013323099,9,19917,WALTON,LINDA,L,NaN,1940-08-16,1966-09-28,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,X,NaN,NaN
1870171,OH0024292091,21,265612,LENTZ,JEFFREY,JOSEPH,NaN,1950-08-16,2017-05-30,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2060288,OH0018281692,9,447847,MCINTOSH,ASHLEY,E,NaN,1987-03-23,2014-03-20,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1630732,OH0015085407,18,1712478,HERNANDEZ,JOSE,L,NaN,1960-10-02,2012-09-10,ACTIVE,...,X,D,NaN,NaN,X,NaN,NaN,X,NaN,NaN
2097775,OH0014663015,18,440280,LUIKART,KATHLEEN,R,NaN,1926-08-23,1900-01-01,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,X,NaN,NaN
1225868,OH0020827481,3,9628603,CLARK,JAMES,ALLEN,NaN,1991-02-02,2009-08-20,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51941,OH0016490514,21,61352,CATTELL,THERESA,A,NaN,1963-02-21,1995-08-05,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,NaN,NaN,X
1143327,OH0014616624,18,346504,GONZALES,GENE,A,NaN,1956-06-25,1900-01-01,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1711583,OH0019289961,13,6088611,ARMACOST,MARY,KATYA,NaN,1964-12-08,2015-10-19,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,X,R,NaN
516451,OH0024676673,15,9960999,DORSEY,AMBER,NICOLE,NaN,1997-08-13,2018-07-04,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1264212,OH0024395220,18,2802798,MCCORMICK,ELLEN,NaN,NaN,1990-04-11,2017-10-23,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1537008,OH0022262867,3,9635054,SWORD,NICOLE,LEE,NaN,1985-10-24,2015-10-13,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
2070038,OH0021744326,12,8801535,MOWELL,ANITA,J,NaN,1969-10-18,2012-04-06,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN
793572,OH0015705700,18,2109490,MORROW,TRENDA,NaN,NaN,1965-01-03,2004-10-01,ACTIVE,...,X,D,NaN,NaN,X,NaN,X,NaN,NaN,NaN
1684279,OH0024719849,9,674489,DUNCAN,ARYANNA,DAWN ROYCE,NaN,2000-05-01,2018-08-07,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276843,OH0024337114,11,193408,STEELE,JEREMY,B,NaN,1976-11-18,2017-07-24,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
905165,OH0014633513,18,383521,LADD,MARILYN,NaN,NaN,1965-10-20,1900-01-01,ACTIVE,...,X,D,NaN,NaN,X,NaN,NaN,NaN,D,NaN
1355316,OH0022714354,18,2631733,ZIMBARDI,KRISTEN,M,NaN,1974-02-20,2014-03-18,CONFIRMATION,...,X,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
697689,OH0023768465,18,2734504,BOHANON,KRYSTAL,NaN,NaN,1990-08-01,2017-09-09,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889575,OH0019955829,9,494383,HOPPER,LINDA,S,NaN,1947-06-23,2017-10-04,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1791045,OH0024517980,18,2815754,BRUCKNER,SUSAN,LYNN,NaN,1953-03-22,2018-03-01,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1830123,OH0011505345,15,7900333,CONNOR,CRAIG,WAYNE,NaN,1961-02-07,1979-02-09,ACTIVE,...,X,D,NaN,NaN,X,NaN,NaN,X,NaN,NaN
1549324,OH0015140969,18,1778620,SHEPARD,STELLA,NaN,NaN,1950-04-05,2012-01-10,ACTIVE,...,NaN,D,NaN,NaN,X,NaN,NaN,X,NaN,NaN
506611,OH0012263459,3,7700289,ARMSTRONG,MARLENE,W,NaN,1953-07-13,1977-11-08,ACTIVE,...,X,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN
558647,OH0010424848,19,7805827,HEMMELGARN,VIVIAN,DIANNE,NaN,1949-10-19,1978-05-03,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,NaN,R,NaN
61608,OH0020541250,18,2425517,YETTKE,STEVEN,M,NaN,1991-01-03,2014-01-15,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209696,OH0022346667,18,2601615,FILIPPI,PEGGY,ANN,NaN,1945-03-16,2013-03-25,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
848130,OH0016435996,21,131662,GUZY,RAYLENE,MARIE,NaN,1941-06-07,2004-02-02,ACTIVE,...,X,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN
2151805,OH0022174789,18,2588900,SMITH,DENNIS,P,NaN,1958-12-28,2012-10-09,ACTIVE,...,X,D,NaN,NaN,X,NaN,NaN,X,D,NaN
1254661,OH0012635164,17,2747,KOCHER,ADAM,P,NaN,1983-04-13,2009-11-03,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
844606,OH0014638398,18,393057,MCNATT,RAYMOND,P,NaN,1964-08-22,2018-07-30,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,X,X,NaN
1217650,OH0015340437,18,1996989,PERLOVA,RAISA,NaN,NaN,1932-12-15,2015-07-08,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
913604,OH0020418221,3,9626952,BRINKER,CHRISTINA,JOY,NaN,1979-02-16,2016-10-05,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1195791,OH0014893074,18,837254,MERVAR,CAROL,L,NaN,1962-08-15,2005-08-15,ACTIVE,...,X,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN
855113,OH0019248283,9,476290,ALLEN,MICHELLE,R,NaN,1988-12-04,2016-03-18,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
114581,OH0019831719,18,2340974,LANDRUM,MICHAEL,A,NaN,1968-10-03,2010-10-04,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1611157,OH0022145364,18,2582578,WILLIAMS,CAROLYN,NaN,NaN,1963-09-29,2016-07-11,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,D,NaN
130204,OH0019051816,18,2245806,MORERE,JACQUELINE,A,NaN,1983-01-02,2011-07-27,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
808383,OH0010311717,4,8701263,DREES,BRIAN,R,NaN,1969-10-06,1987-12-01,ACTIVE,...,X,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1220703,OH0018555216,18,2181657,CAMMON,SHIRLEY,A,NaN,1949-08-25,2005-09-01,ACTIVE,...,X,D,NaN,NaN,X,X,X,X,D,NaN
1912299,OH0011133224,20,8200079,WILES,SUSAN,R,NaN,1963-12-20,1982-02-18,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1609453,OH0014694785,18,502160,STEMPFER,IRENE,NaN,NaN,1928-03-02,1981-09-22,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
560781,OH0023871201,18,2748033,JONES,NATHAN,C,NaN,1998-06-25,2016-08-22,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1823726,OH0014886938,18,826732,KUNZ,DIANE,M,NaN,1950-08-01,2013-11-05,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
2079932,OH0021383514,14,10607863,LEMMINGS,THOMAS,E,NaN,1974-12-03,2011-04-28,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152377,OH0020207927,2,1018956,LUGABIHL,CAROL,A,NaN,1939-12-15,2008-10-06,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,X,R,NaN
986642,OH0022343088,4,9651096,GULLO,THOMAS,J,NaN,1995-03-02,2013-03-19,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1203192,OH0021029421,18,2452610,MILLER,GREGORY,R,NaN,1967-04-01,2010-04-05,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607935,OH0024738199,19,9633749,THORNTON,ERIC,RAYMOND,NaN,1977-06-22,2018-08-28,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1655196,OH0021327838,18,2481133,POCKYNOK,YAROSLAW,NaN,NaN,1938-10-08,2011-03-04,CONFIRMATION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1327822,OH0011529135,15,8402224,KOSKO,BETSY,J,NaN,1960-10-14,1984-09-27,ACTIVE,...,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,NaN
1580039,OH0010271647,8,9905723,ADAMS,CATHERINE,NaN,NaN,1953-03-28,2016-02-04,ACTIVE,...,X,D,NaN,NaN,X,NaN,NaN,NaN,D,NaN
1681675,OH0023602077,18,2712131,STEWART,SYANNE,L,NaN,1997-08-12,2018-02-16,ACTIVE,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,D,NaN
1715905,OH0017931950,13,498475,TOMLIN,TIMOTHY,D,NaN,1948-09-14,1972-09-25,ACTIVE,...,X,D,NaN,NaN,X,NaN,NaN,X,NaN,NaN
2001622,OH0024674955,18,2832813,DAHN,MIAGHEN,SIENA,NaN,1985-05-16,2018-07-05,ACTIVE,...,X,D,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
1667161,OH0021851344,13,6129870,KING,DUSTIN,J,NaN,1994-05-23,2012-07-13,ACTIVE,...,X,R,NaN,NaN,X,NaN,NaN,X,NaN,NaN

In [5]:
sample2 = sample2.head(500)
sample3 = sample3.head(500)
sample4 = sample4.head(500)

In [6]:
sample1.to_csv("1_22_sample.csv")
sample2.to_csv("23_44_sample.csv")
sample3.to_csv("45_66_sample.csv")
sample4.to_csv("67_88_sample.csv")